'dev experience':
  - .github/**/*
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
  - .gitignore
  - .prettierignore
  - .prettierrc
  - README.md
dependencies:
  - package.json
  - yarn.lock
website:
  - src/**/*
  - docusaurus.config.js
blog: blog/**/*
wiki: docs/wiki/**/*
'docs: algorithm': docs/algorithm/**/*
'docs: css': docs/css/**/*
'docs: design patterns': docs/design-patterns/**/*
'docs: html': docs/html/**/*
'docs: javascript': docs/javascript/**/*
'docs: react': docs/react/**/*
'docs: browser': docs/browser/**/*
'docs: linux': docs/linux/**/*
'docs: web security': docs/web-security/**/*
'docs: http': docs/http/**/*
'docs: typescript': docs/typescript/**/*
'docs: webpack': docs/webpack/**/*
'docs: nodejs': docs/nodejs/**/*
'docs: python': docs/python/**/*
'docs: go': docs/go/**/*
'docs: sql': docs/sql/**/*
'docs: svg': docs/svg/**/*
'docs: git': docs/git/**/*
'docs: fastapi': docs/fastapi/**/*
'docs: docker': docs/docker/**/*
'docs: kubernetes': docs/kubernetes/**/*
'docs: data viz': docs/data-viz-guide/**/*
