'dev experience':
  - .github/**/*
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
  - .gitignore
  - .prettierignore
  - .prettierrc
  - README.md
dependencies:
  - package.json
  - yarn.lock
website:
  - src/**/*
  - docusaurus.config.js
blog: blog/**/*
wiki: docs/wiki/**/*
'docs: ds & algorithm': docs/algorithm/**/*
'docs: css': docs/css/**/*
'docs: design patterns': docs/design-patterns/**/*
'docs: html': docs/html/**/*
'docs: javascript': docs/javascript/**/*
'docs: react stack': docs/react/**/*
'docs: web': docs/web/**/*
'docs: network': docs/http/**/*
'docs: typescript': docs/typescript/**/*
'docs: webpack': docs/webpack/**/*
'docs: nodejs': docs/nodejs/**/*
'docs: python': docs/python/**/*
'docs: go': docs/go/**/*
'docs: mysql': docs/mysql/**/*
'docs: svg': docs/svg/**/*
'docs: git': docs/git/**/*
'docs: docker': docs/docker/**/*
'docs: data viz guidebook': docs/data-viz-guidebook/**/*
