name-template: 'release-v$NEXT_PATCH_VERSION'
tag-template: 'release-v$NEXT_PATCH_VERSION'
categories:
  - title: 'Blog'
    labels:
      - 'blog'
  - title: 'Algorithm'
    labels:
      - 'docs: algorithm'
  - title: 'Design patterns'
    labels:
        - 'docs: design patterns'
  - title: 'HTML'
    labels:
        - 'docs: html'
  - title: 'CSS'
    labels:
        - 'docs: css'
  - title: 'Javascript'
    labels:
        - 'docs: javascript'
  - title: 'React'
    labels:
        - 'docs: react'
  - title: 'Web'
    labels:
        - 'docs: web'
  - title: 'Java'
    labels:
        - 'docs: java'
  - title: 'HTTP'
    labels:
        - 'docs: http'
  - title: 'Typescript'
    labels:
      - 'docs: typescript'
  - title: 'Website'
    labels:
      - 'website'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # What's Changed

  $CHANGES
