name-template: '2023.x'
tag-template: '2023.x'
sort-by: 'title'
sort-direction: 'ascending'
exclude-labels:
  - 'dependencies'
  - 'security'
categories:
  - title: 'Basics'
    labels:
      - 'docs: data structures'
      - 'docs: algorithms'
      - 'docs: design patterns'
      - 'docs: http'
      - 'docs: browser'
      - 'docs: web security'
      - 'docs: linux'
      - 'docs: git'
      - 'docs: macos'
  - title: 'Frontend'
    labels:
      - 'docs: javascript'
      - 'docs: html'
      - 'docs: css'
      - 'docs: react'
      - 'docs: webpack'
      - 'docs: typescript'
      - 'docs: nodejs'
  - title: 'Backend'
    labels:
      - 'docs: python'
      - 'docs: fastapi'
      - 'docs: sqlalchemy'
      - 'docs: sql'
      - 'docs: docker'
      - 'docs: kubernetes'
  - title: 'Data & AI'
    labels:
      - 'docs: data viz'
      - 'docs: svg'
  - title: 'Blog'
    labels:
      - 'blog'
  - title: 'Others'
    labels:
      - 'dev experience'
      - 'wiki'
      - 'website'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # Changes

  $CHANGES
