name-template: '2022.xx'
tag-template: '2022.xx'
sort-by: 'title'
sort-direction: 'ascending'
exclude-labels:
  - 'dependencies'
  - 'security'
categories:
  - title: 'Basics'
    labels:
      - 'docs: algorithm'
      - 'docs: design patterns'
      - 'docs: http'
  - title: 'Frontend'
    labels:
      - 'docs: javascript'
      - 'docs: html'
      - 'docs: css'
      - 'docs: web'
      - 'docs: react'
      - 'docs: webpack'
      - 'docs: typescript'
      - 'docs: nodejs'
      - 'docs: fe guidelines'
  - title: 'Backend'
    labels:
      - 'docs: python'
      - 'docs: go'
      - 'docs: mysql'
  - title: 'Data & AI'
    labels:
      - 'docs: svg'
  - title: 'Blog'
    labels:
      - 'blog'
  - title: 'Others'
    labels:
      - 'dev experience'
      - 'wiki'
      - 'website'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # Changes

  $CHANGES
