name-template: '2020-Q?-M?'
tag-template: '2020-Q?-M?'
sort-by: 'title'
exclude-labels:
  - 'dependencies'
categories:
  - title: 'Basis'
    labels:
      - 'docs: algorithm'
      - 'docs: design patterns'
      - 'docs: http'
  - title: 'Frontend'
    labels:
      - 'docs: javascript'
      - 'docs: html'
      - 'docs: css'
      - 'docs: web'
      - 'docs: react'
      - 'docs: webpack'
      - 'docs: typescript'
  - title: 'Backend'
    labels:
      - 'docs: java'
  - title: 'Blog'
    labels:
      - 'blog'
  - title: 'Wiki'
    labels:
      - 'wiki'
  - title: 'Website'
    labels:
      - 'website'
  - title: 'Dev experience'
    labels:
      - 'dev experience'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # Changes

  $CHANGES
