name-template: '2020-Q?-M?'
tag-template: '2020-Q?-M?'
categories:
  - title: 'Blog'
    labels:
      - 'blog'
  - title: 'Algorithm'
    labels:
      - 'docs: algorithm'
  - title: 'Design patterns'
    labels:
        - 'docs: design patterns'
  - title: 'HTTP'
    labels:
        - 'docs: http'
  - title: 'Javascript'
    labels:
        - 'docs: javascript'
  - title: 'Typescript'
    labels:
      - 'docs: typescript'
  - title: 'CSS'
    labels:
        - 'docs: css'
  - title: 'HTML'
    labels:
        - 'docs: html'
  - title: 'Web'
    labels:
        - 'docs: web'
  - title: 'React'
    labels:
        - 'docs: react'
  - title: 'Webpack'
    labels:
      - 'docs: webpack'
  - title: 'NodeJs'
    labels:
      - 'docs: nodejs'
  - title: 'Java'
    labels:
      - 'docs: java'
  - title: 'Wiki'
    labels:
      - 'wiki'
  - title: 'Website'
    labels:
      - 'website'
  - title: 'Dev experience'
    labels:
      - 'dev experience'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # What's Changed

  $CHANGES
