name-template: '2020-Q?-M?'
tag-template: '2020-Q?-M?'
sort-by: 'title'
sort-direction: 'ascending'
exclude-labels:
  - 'dependencies'
  - 'security'
categories:
  - title: 'Basis'
    labels:
      - 'docs: algorithm'
      - 'docs: design patterns'
      - 'docs: http'
  - title: 'Frontend'
    labels:
      - 'docs: javascript'
      - 'docs: html'
      - 'docs: css'
      - 'docs: web'
      - 'docs: react'
      - 'docs: webpack'
      - 'docs: typescript'
      - 'docs: nodejs'
      - 'docs: fe guidelines'
  - title: 'Backend'
    labels:
      - 'docs: java'
  - title: 'Blog'
    labels:
      - 'blog'
  - title: 'Others'
    labels:
      - 'dev experience'
      - 'wiki'
      - 'website'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # Release Note

  $CHANGES
