language: node_js
node_js:
  - "8.9.0"
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run lib
  - npm run dist
  - npm run site:dist
notifications:
    slack: g-explorer:81CbfYw9kEml7k1QcXQkGfrB
