name: auto-merge

on:
  check_suite:
    types:
      - completed

jobs:
  merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
