name: pr-title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^[a-z]+\(.+\):\s.+$'
          allowed_prefixes: 'add,update,fix,build,revert'
          prefix_case_sensitive: true
          min_length: 5
          max_length: 50
