name: pr-triage

# https://github.com/actions/labeler/issues/12#issuecomment-991806288
on: pull_request_target

jobs:
  add-reviewers-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
